### ISSUE TITLE
Perform incremental compilation using official compiler API

### ISSUE THREAD

**Issue by fwcd** [fwcd/KotlinLanguageServer#12]
Investigate support for incremental compilation using the [official Kotlin compiler API](https://github.com/JetBrains/kotlin/tree/master/compiler/incremental-compilation-impl) instead of the mechanism currently used ([as described in the README](https://github.com/fwcd/KotlinLanguageServer/blob/master/README.md#this-repository-needs-your-help)), because this might improve performance considerably.

**Comment by fwcd** [comment]
This might be related:
```
Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.util.Arrays.copyOfRange(Arrays.java:3664)
	at java.lang.String.<init>(String.java:207)
	at java.lang.String.substring(String.java:1969)
	at java.lang.String.subSequence(String.java:2003)
	at kotlin.text.StringsKt__StringsKt.commonPrefixWith(Strings.kt:775)
	at kotlin.text.StringsKt__StringsKt.commonPrefixWith$default(Strings.kt:765)
	at org.javacs.kt.position.PositionKt.changedRegion(position.kt:95)
	at org.javacs.kt.CompiledFile.oldOffset(CompiledFile.kt:114)
	at org.javacs.kt.CompiledFile.parseAtPoint(CompiledFile.kt:72)
	at org.javacs.kt.signatureHelp.SignatureHelpKt.signatureHelpAt(signatureHelp.kt:22)
	at org.javacs.kt.KotlinTextDocumentService.signatureHelp(KotlinTextDocumentService.kt:128)
	at sun.reflect.GeneratedMethodAccessor76.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:61)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint$$Lambda$35/698288148.apply(Unknown Source)
```

**Comment by apatrida** [comment]
Is incremental compilation needed for code completion or for what purpose?  How does the kotlin-web-demo handle completion?

https://github.com/JetBrains/kotlin-web-demo/tree/master/versions/1.2.50/src/main/java/org/jetbrains/webdemo/kotlin/impl

**Comment by fwcd** [comment]
@apatrida Each file needs to be compiled to an abstract syntax tree by the Kotlin compiler frontend. Using the AST, the language server can provide document symbols, code completion, hover and more.

The naive solution to this problem would be to compile the entire file every time the user makes an edit, but that would be extremly slow (and make your editor feel laggy). To address this problem, the language server currently extracts the expression around the cursor, puts it into a small "fake" file and tells the compiler to compile the "fake" file. Still, it would probably be better to use official compiler APIs as mentioned in the issue description.

I will take a look at the Kotlin Demo code soon (which does not provide any code completion unfortunately, but seems promising regarding performance).

**Comment by fwcd** [comment]
@Strum355 I have created a Gitter channel for this project:

[![Gitter](https://badges.gitter.im/fwcd-projects/KotlinLanguageServer.png)](https://gitter.im/fwcd-projects/KotlinLanguageServer)

**Comment by fwcd** [comment]
@Strum355 There is a new Gitter channel for this project:

[![Gitter](https://badges.gitter.im/fwcd-projects/KotlinLanguageServer.png)](https://gitter.im/fwcd-projects/KotlinLanguageServer)

**Comment by weilbith** [comment]
Sounds very promising to improve performance. Is it complicated to add this?
