### ISSUE TITLE
Java to Kotlin converter fails in AnnotationConverter

### ISSUE THREAD

**Issue by fwcd** [fwcd/KotlinLanguageServer#24]
```
java.lang.NullPointerException
	at org.jetbrains.kotlin.j2k.AnnotationConverter.<init>(AnnotationConverter.kt:31)
	at org.jetbrains.kotlin.j2k.Converter.<init>(Converter.kt:60)
	at org.jetbrains.kotlin.j2k.Converter.<init>(Converter.kt:40)
	at org.jetbrains.kotlin.j2k.Converter$Companion.create(Converter.kt:71)
	at org.jetbrains.kotlin.j2k.JavaToKotlinConverter$elementsToKotlin$intermediateResults$1.invoke(JavaToKotlinConverter.kt:109)
	at org.jetbrains.kotlin.j2k.JavaToKotlinConverter$elementsToKotlin$intermediateResults$1.invoke(JavaToKotlinConverter.kt:48)
	at org.jetbrains.kotlin.j2k.JavaToKotlinConverter$WithProgressProcessor$processItems$1.run(JavaToKotlinConverter.kt:258)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:543)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:488)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at org.jetbrains.kotlin.j2k.JavaToKotlinConverter$WithProgressProcessor.processItems(JavaToKotlinConverter.kt:248)
	at org.jetbrains.kotlin.j2k.JavaToKotlinConverter.elementsToKotlin(JavaToKotlinConverter.kt:108)
	at org.jetbrains.kotlin.j2k.JavaToKotlinConverter.elementsToKotlin(JavaToKotlinConverter.kt:94)
	at org.javacs.kt.javaToKotlin.JavaToKotlinConverterKt.convertJavaToKotlin(javaToKotlinConverter.kt:54)
	at org.javacs.kt.KotlinWorkspaceService.executeCommand(KotlinWorkspaceService.kt:40)
	... 16 more
```

This null pointer might be caused by an incompatible kotlin-converter.jar version. Unfortunately, the JetBrains/kotlin/j2k module has not been published to Maven central, which makes it hard to optain a current version of this dependency.

**Comment by fwcd** [comment]
![j2k](https://user-images.githubusercontent.com/30873659/42115819-e10afdca-7bf4-11e8-9e86-e05f9265db2a.gif)
