### ISSUE TITLE
Build exception on windows 7 "javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed”

### ISSUE THREAD

**Issue by zijianyue** [fwcd/KotlinLanguageServer#94]
G:\lsp\KotlinLanguageServer>gradlew build
Downloading https://services.gradle.org/distributions/gradle-4.6-bin.zip

Exception in thread "main" javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
        at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1946)
        at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:316)
        at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:310)
        at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1639)
        at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:223)
        at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1037)
        at sun.security.ssl.Handshaker.process_record(Handshaker.java:965)
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1064)
        at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1367)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1395)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1379)
        at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263)
        at org.gradle.wrapper.Download.downloadInternal(Download.java:66)
        at org.gradle.wrapper.Download.download(Download.java:51)
        at org.gradle.wrapper.Install$1.call(Install.java:62)
        at org.gradle.wrapper.Install$1.call(Install.java:48)
        at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:69)
        at org.gradle.wrapper.Install.createDist(Install.java:48)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:107)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:397)
        at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:302)
        at sun.security.validator.Validator.validate(Validator.java:262)
        at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324)
        at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:229)
        at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124)
        at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1621)
        ... 20 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
        at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
        at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280)
        at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:392)
        ... 26 more

G:\lsp\KotlinLanguageServer>

**Comment by fwcd** [comment]
Did you check https://stackoverflow.com/questions/29584328/gradlew-bat-and-gradlew-sslhandshakeexception?

**Comment by zijianyue** [comment]
I tried below method and it worked.My company internet is behind proxy and using firewall , but I configured gradle.properties by adding proxy, and I can access https://services.gradle.org/distributions/gradle-4.6-bin.zip using browser, so it's weird.


> _If you could not fix anyway. and if you are inside firewall.
> then.
> you may can not download https.
> 
> should fix that Edit gradle-wrapper.properties file.
> 
> vi [project]/gradle/wrapper/gradle-wrapper.properties
> 
> #distributionUrl=https\://services.gradle.org/distributions/gradle-2.8-bin.zip 
> distributionUrl=http\://services.gradle.org/distributions/gradle-2.8-bin.zip
> change from https to http..._


**And then the build still failed as below:**

> G:\lsp\KotlinLanguageServer>gradlew build
> Downloading http://services.gradle.org/distributions/gradle-4.6-bin.zip
> ......................................................................
> Unzipping C:\Users\me\.gradle\wrapper\dists\gradle-4.6-bin\duhtpboxeoghujb3mpu8wvikb\gradle-4.6-bin.zip to C:\Users\me\.gradle\wrapper\dists\gradle-4.6-bin\duhtpboxeoghujb3mpu8wvikb
> Starting a Gradle Daemon (subsequent builds will be faster)
> Download https://plugins.gradle.org/m2/com/github/jk1/tcdeps/com.github.jk1.tcdeps.gradle.plugin/0.17/com.github.jk1.tcdeps.gradle.plugin-0.17.pom
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> A problem occurred configuring root project 'kotlin-language-server'.
> > Could not resolve all artifacts for configuration ':classpath'.
>    > Could not resolve org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.11.
>      Required by:
>          project :
>       > Could not resolve org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.11.
>          > Could not get resource 'https://plugins.gradle.org/m2/org/jetbrains/kotlin/kotlin-gradle-plugin/1.3.11/kotlin-gradle-plugin-1.3.11.pom'.
>             > Could not GET 'https://plugins.gradle.org/m2/org/jetbrains/kotlin/kotlin-gradle-plugin/1.3.11/kotlin-gradle-plugin-1.3.11.pom'.
>                > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
>       > Could not resolve org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.11.
>          > Could not get resource 'https://repo.maven.apache.org/maven2/org/jetbrains/kotlin/kotlin-gradle-plugin/1.3.11/kotlin-gradle-plugin-1.3.11.pom'.
>             > Could not GET 'https://repo.maven.apache.org/maven2/org/jetbrains/kotlin/kotlin-gradle-plugin/1.3.11/kotlin-gradle-plugin-1.3.11.pom'.
>                > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
>    > Could not resolve gradle.plugin.com.github.jk1:tcdeps:0.17.
>      Required by:
>          project : > com.github.jk1.tcdeps:com.github.jk1.tcdeps.gradle.plugin:0.17
>       > Could not resolve gradle.plugin.com.github.jk1:tcdeps:0.17.
>          > Could not get resource 'https://plugins.gradle.org/m2/gradle/plugin/com/github/jk1/tcdeps/0.17/tcdeps-0.17.pom'.
>             > Could not GET 'https://plugins.gradle.org/m2/gradle/plugin/com/github/jk1/tcdeps/0.17/tcdeps-0.17.pom'.
>                > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
>       > Could not resolve gradle.plugin.com.github.jk1:tcdeps:0.17.
>          > Could not get resource 'https://repo.maven.apache.org/maven2/gradle/plugin/com/github/jk1/tcdeps/0.17/tcdeps-0.17.pom'.
>             > Could not GET 'https://repo.maven.apache.org/maven2/gradle/plugin/com/github/jk1/tcdeps/0.17/tcdeps-0.17.pom'.
>                > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 2m 19s
